### ISSUE TITLE
Remote Monitor crash

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#112]
Shift-clicking a card into the Remote Monitor yielding this...
```
	at shedar.mods.ic2.nuclearcontrol.containers.ContainerRemoteMonitor.slotClick(ContainerRemoteMonitor.java:55)
	at net.minecraft.inventory.Container.retrySlotClick(Container.java:517)
	at net.minecraft.inventory.Container.slotClick(Container.java:288)
```
with a crash, repeating about one hundred times (sorry for being very unspecific, just try replicating it).

Cards can be placed inside normally though, this is good. Clicking a card out will drop that card on the ground, which is a bit silly.

**Comment by xbony2** [comment]
I think the numbers of the Energy Sensor Location Card may be off for RF stuff, it appears differently in WAILA vs. the card,
