### ISSUE TITLE
crash when inserting Reactor SLC into Adv.Inf.Panel (2.2.5a works fine)

### ISSUE THREAD

**Issue by lex1975** [xbony2/Nuclear-Control#114]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 10/8/15 7:59 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at shedar.mods.ic2.nuclearcontrol.panel.CardWrapperImpl.setBoolean(CardWrapperImpl.java:160)
	at shedar.mods.ic2.nuclearcontrol.items.ItemCard55Reactor.update(ItemCard55Reactor.java:53)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:710)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:735)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shedar.mods.ic2.nuclearcontrol.panel.CardWrapperImpl.setBoolean(CardWrapperImpl.java:160)
	at shedar.mods.ic2.nuclearcontrol.items.ItemCard55Reactor.update(ItemCard55Reactor.java:53)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:710)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:735)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1b6fcc64
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 208774400 bytes (199 MB) / 484028416 bytes (461 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -Xmx3072M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:MaxPermSize=1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
	UCHIJAAAAAAAAA	IC2{2.2.766-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.766-experimental.jar) 
	UCHIJAAAAAAAAA	IC2NuclearControl{2.3.0a-Butt} [Nuclear Control 2] (IC2NuclearControl-2.3.0a-Butt.jar) 
	UCHIJAAAAAAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10.jar) 
	UCHIJAAAAAAAAA	modtweaker2{0.9.2} [Mod Tweaker 2] (ModTweaker2-0.9.3.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['lex1975'/693, l='Новый мир', x=-527.15, y=64.00, z=185.09]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by dmf444** [comment]
This is confirmed, issue with trying to access whether the Reactor is on/off. Working on it ATM
