### ISSUE TITLE
Crash when drop portable information panel from opened container

### ISSUE THREAD

**Issue by Ghostlyr** [xbony2/Nuclear-Control#122]
```
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at shedar.mods.ic2.nuclearcontrol.InventoryItem.<init>(InventoryItem.java:23)
	at shedar.mods.ic2.nuclearcontrol.gui.GuiRemoteMonitor.func_146979_b(GuiRemoteMonitor.java:63)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shedar.mods.ic2.nuclearcontrol.InventoryItem.<init>(InventoryItem.java:23)
	at shedar.mods.ic2.nuclearcontrol.gui.GuiRemoteMonitor.func_146979_b(GuiRemoteMonitor.java:63)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)

-- Screen render details --
Details:
	Screen name: shedar.mods.ic2.nuclearcontrol.gui.GuiRemoteMonitor
	Mouse location: Scaled: (441, 322). Absolute: (882, 383)
	Screen size: Scaled: (960, 514). Absolute: (1920, 1028). Scale factor of 2
```

**Comment by xbony2** [comment]
Like by throwing a Portable Info Panel out of a chest?

**Comment by Ghostlyr** [comment]
Out of player inventory from opened panel GUI. Moving portable info item from opened inventory crashes minecraft too.

**Comment by xbony2** [comment]
Did said Portal Info Panel have a card in it? Or does that not matter?

**Comment by Ghostlyr** [comment]
No matter.

**Comment by Ghostlyr** [comment]
I have compiled the last mod source. Thanks, simple forbiddance resolves variant with separately item drop from opened container. But when portable panel has been simultaneously opened end dropped (Right click + Q) client freezes and kicks me with "fatal error connection terinated" reason.
Errors in log-file:

```
[03:33:29] [Client thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at shedar.mods.ic2.nuclearcontrol.network.message.PacketClientRemoteMonitor$Handler.onMessage(PacketClientRemoteMonitor.java:140) ~[PacketClientRemoteMonitor$Handler.class:?]
	at shedar.mods.ic2.nuclearcontrol.network.message.PacketClientRemoteMonitor$Handler.onMessage(PacketClientRemoteMonitor.java:134) ~[PacketClientRemoteMonitor$Handler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[03:33:29] [Client thread/ERROR]: There was a critical exception handling a packet on channel IC2NC
java.lang.NullPointerException
	at shedar.mods.ic2.nuclearcontrol.network.message.PacketClientRemoteMonitor$Handler.onMessage(PacketClientRemoteMonitor.java:140) ~[PacketClientRemoteMonitor$Handler.class:?]
	at shedar.mods.ic2.nuclearcontrol.network.message.PacketClientRemoteMonitor$Handler.onMessage(PacketClientRemoteMonitor.java:134) ~[PacketClientRemoteMonitor$Handler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

These two errors are repeated infinitely until kick.
