### ISSUE TITLE
java.lang.NullPointerException: Initializing game (IC2NuclearControl-2.4.0a)

### ISSUE THREAD

**Issue by Lightone** [xbony2/Nuclear-Control#154]
IC2NuclearControl-2.3.4a this version work fine any issue but today i update a new version and happend that randonw crash when startud the game (Minecraft Launcher) 

`---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 28/05/16 12:12 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.jadarstudios.developercapes.cape.CapeConfigManager.parse(CapeConfigManager.java:93)
	at com.jadarstudios.developercapes.cape.CapeConfigManager.parseFromStream(CapeConfigManager.java:130)
	at com.jadarstudios.developercapes.DevCapes.registerConfig(DevCapes.java:137)
	at shedar.mods.ic2.nuclearcontrol.ClientProxy.cape(ClientProxy.java:70)
	at shedar.mods.ic2.nuclearcontrol.IC2NuclearControl.postInit(IC2NuclearControl.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.jadarstudios.developercapes.cape.CapeConfigManager.parse(CapeConfigManager.java:93)
	at com.jadarstudios.developercapes.cape.CapeConfigManager.parseFromStream(CapeConfigManager.java:130)
	at com.jadarstudios.developercapes.DevCapes.registerConfig(DevCapes.java:137)
	at shedar.mods.ic2.nuclearcontrol.ClientProxy.cape(ClientProxy.java:70)
	at shedar.mods.ic2.nuclearcontrol.IC2NuclearControl.postInit(IC2NuclearControl.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 229417936 bytes (218 MB) / 597884928 bytes (570 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D4 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJ	da3dsoulASMFix{0.1.0} [DA3DSOUL ASM Fixes] (minecraft.jar) 
	UCHIJ	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJ	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJ	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHIJ	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJ	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJ	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJ	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
	UCHIJ	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
	UCHIJ	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
	UCHIJ	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
	UCHIJ	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
	UCHIJ	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
	UCHIJ	Additional-Buildcraft-Objects{MC1.7.10-BC7.1release4.0.9} [Additional Buildcraft Objects] (ABO-MC1.7.10-BC7.1release4.0.9.jar) 
	UCHIJ	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCHIJ	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
	UCHIJ	IC2{2.2.822-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.822-experimental.jar) 
	UCHIJ	Forestry{4.2.12.60} [Forestry for Minecraft] (forestry_1.7.10-4.2.12.60.jar) 
	UCHIJ	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCHIJ	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCHIJ	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
	UCHIJ	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
	UCHIJ	gendustry{1.6.3.132} [GenDustry] (gendustry-1.6.3.132-mc1.7.10.jar) 
	UCHIE	IC2NuclearControl{2.4.0a} [Nuclear Control 2] (IC2NuclearControl-2.4.0a.jar) 
	UCHIJ	LogisticsPipes{0.9.3.121} [Logistics Pipes] (logisticspipes-0.9.3.121.jar) 
	UCHIJ	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJ	Railcraft{9.12.1.0} [Railcraft] (Railcraft_1.7.10-9.12.1.0.jar) 
	UCHIJ	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UCHIJ	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6.jar) 
	UCHIJ	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCHIJ	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
	List of loaded APIs: 
		* bcadditionsAPI (2.1.1) from BuildcraftAdditions-1.7.10-2.2.5.jar
		* BuildCraftAPI|blocks (1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.16.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|core (1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|items (1.1) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|library (2.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|lists (1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.16.jar
		* BuildCraftAPI|recipes (4.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.16.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.16.jar
		* BuildCraftAPI|tiles (1.2) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* BuildCraftAPI|transport (4.1) from Railcraft_1.7.10-9.12.1.0.jar
		* CoFHAPI (1.7.10R1.0.1) from BuildcraftAdditions-1.7.10-2.2.5.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from BuildcraftAdditions-1.7.10-2.2.5.jar
		* CoFHAPI|inventory (1.7.10R1.0.1) from buildcraft-compat-7.1.3.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.3.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.12.60.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.12.60.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.3.132-mc1.7.10.jar
		* IC2API (1.0) from industrialcraft-2-2.2.822-experimental.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.4.0a.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|core (1.5.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|electricity (2.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|locomotive (1.1.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|signals (2.3.0) from Railcraft_1.7.10-9.12.1.0.jar
		* RailcraftAPI|tracks (2.3.0) from Railcraft_1.7.10-9.12.1.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.12.1.0.jar
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)`

**Comment by xJon** [comment]
Any temporary fix, though? It has anything to do with capes?
While a lot of people don't experience this issue, some do, and they cannot play in their servers, which is unfortunate.

**Comment by dmf444** [comment]
I'm working on a final 1.7.10 release, it should be fixed then

**Comment by xJon** [comment]
@dmf444 Thanks :+1:
