### ISSUE TITLE
Console ERROR - java.lang.ClassNotFoundException: mekanism.api.energy.IStrictEnergyStorage

### ISSUE THREAD

**Issue by wollfenss** [xbony2/Nuclear-Control#163]
`[15:47:27] [Server thread/WARN]: java.lang.ClassNotFoundException: mekanism.api.energy.IStrictEnergyStorage
[15:47:27] [Server thread/WARN]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[15:47:27] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[15:47:27] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[15:47:27] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[15:47:27] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:278)
[15:47:27] [Server thread/WARN]: 	at shedar.mods.ic2.nuclearcontrol.crossmod.mekanism.CrossMekanism.<init>(CrossMekanism.java:16)
[15:47:27] [Server thread/WARN]: 	at shedar.mods.ic2.nuclearcontrol.crossmod.CrossModLoader.postinit(CrossModLoader.java:30)
[15:47:27] [Server thread/WARN]: 	at shedar.mods.ic2.nuclearcontrol.IC2NuclearControl.postInit(IC2NuclearControl.java:207)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:47:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[15:47:27] [Server thread/WARN]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:47:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:47:27] [Server thread/WARN]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[15:47:27] [Server thread/WARN]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[15:47:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:47:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[15:47:27] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[15:47:27] [Server thread/WARN]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[15:47:27] [Server thread/WARN]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[15:47:27] [Server thread/WARN]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[15:47:27] [Server thread/WARN]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
[15:47:27] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:288)
[15:47:27] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[15:47:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:47:27] [Server thread/WARN]: Caused by: java.lang.NullPointerException`

MODS: 
![screenshot_1](https://cloud.githubusercontent.com/assets/16450229/16950772/89883572-4dca-11e6-8770-fd2fdc348852.png)

**Comment by Andrey228322** [comment]
up

**Comment by Andrey228322** [comment]
What to do?

**Comment by xbony2** [comment]
Nothing.
