### ISSUE TITLE
Nuclear Control 2 MC 1.7.10

### ISSUE THREAD

**Issue by Markus1990mg** [xbony2/Nuclear-Control#181]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at shedar.mods.ic2.nuclearcontrol.crossmod.bigreactors.ItemCardRFSensor.update(ItemCardRFSensor.java:53)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:714)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:739)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_145845_h(TileEntityInfoPanel.java:406)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shedar.mods.ic2.nuclearcontrol.crossmod.bigreactors.ItemCardRFSensor.update(ItemCardRFSensor.java:53)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:714)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:739)
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_145845_h(TileEntityInfoPanel.java:406)

-- Block entity being ticked --
Details:
	Name: IC2NCAdvancedInfoPanel // shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityAdvancedInfoPanel
	Block type: ID #917 (tile.null // shedar.mods.ic2.nuclearcontrol.blocks.BlockNuclearControlMain)
	Block data value: 9 / 0x9 / 0b1001
	Block location: World: (-710,98,426), Chunk: (at 10,6,10 in -45,26; contains blocks -720,0,416 to -705,255,431), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Actual block type: ID #917 (tile.null // shedar.mods.ic2.nuclearcontrol.blocks.BlockNuclearControlMain)
	Actual block data value: 9 / 0x9 / 0b1001
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by xJon** [comment]
Got another report of this issue today, using the latest version (`2.4.5a`).

**Comment by xbony2** [comment]
Life is unfortunately too busy for me to try to work on this mod anymore, and setting up the dev environment for a version as ancient as this is also a nightmare. Honestly impressive that I got it to work two years ago. Unfortunate that my old computer for MC mod dev has had power issues and is too old to support modern software anyway.

**Comment by xJon** [comment]
1.7.10 is actually quite well maintained by the GTNH team, they have [RetroFuturaGradle](https://github.com/GTNewHorizons/RetroFuturaGradle/tree/master/example) but also seemingly a [Nuclear Control fork](https://github.com/GTNewHorizons/Nuclear-Control).

**Comment by xbony2** [comment]
Yeah they have quite a project, it makes me happy to see that it's still around and that they're still doing that. Too bad no capes :P that was my favorite NC2 feature
